name: CI Docker Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker compose -f docker-compose.yml build

      - name: Run tests
        run: docker compose -f docker-compose.yml run --rm backend npm test

      - name: Push image to Docker Hub
        run: |
          docker compose -f docker-compose.yml build backend
          docker tag $(docker compose -f docker-compose.yml images -q backend) blackfargo/backend_service:latest
          docker push blackfargo/backend_service:latest
